name: Package Application with Pyinstaller

on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: install req
        run: pip install -r requirements.txt;
        
      - name: dl upx
        run: python .github\getLatestUPX.py; 7z x upx.zip; mv upx-* upx;
      
      - name: pack
        run: pyinstaller --upx-dir upx ChessGameCollection.spec -y ; mv dist\ChessGameCollection.exe ./;
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ChessGameCollection.exe
          path: ChessGameCollection.exe
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ChessGameCollection.exe
          asset_name: ChessGameCollection.exe
          tag: ${{ github.ref }}

